### ISSUE TITLE
Container startet nicht

### ISSUE THREAD

**Issue by giss69** [realdadfish/teslawallconnector#1]
Hallo,

aus dem äff Forum.))
Wenn ich command :"$ ash -x ./build-and-run.sh"
kommt bei mir 
"-ash: $: command not found"
Wenn ich meine Daten in Dateien eingebe, soll ein neues Image gebildet werden, oder?
Danke für Deine Mühe!

Update: ohne $ hat es geklappt!

**Comment by realdadfish** [comment]
Am 2021-11-25 17:07, schrieb giss69:
> Hallo,
> 
> aus dem äff Forum.))
> Wenn ich command :"$ ash -x ./build-and-run.sh"
> kommt bei mir
> "-ash: $: command not found"
> Wenn ich meine Daten in Dateien eingebe, soll ein neues Image gebildet
> werden, oder?
> Danke für Deine Mühe!


Moin!

Ich glaube, das ist ein Missverständnis :)

Wenn man bei Codebeispielen ein "$" vorne an stellt, bedeutet das, das 
man das Codebeispiel in einer Shell ausführen muss, weil die meisten 
Shells ein "$" als sog. "Prompt" nutzen.

Also einfach immer ohne das führende "$" ausführen. Wenn bei der 
Ausführung dann bei Dir Probleme auftauchen, kannst Du wiederrum mit 
"ash -x Kommando" einzeln ausgeben lassen, was das Skript macht. So 
findet man dann leichter das Problem, aber hoffen wir erst einmal, dass 
es schon so wie es ist klappt :)

Viele Grüße,
Thomas.

-- 
GPG-Key 0xCD45F2FD | Skype: realdeadfish | https://www.thomaskeller.biz
Please note that according to the EU law on data retention, information
on every electronic information exchange might be retained for a period
of six months or longer: http://www.vorratsdatenspeicherung.de/?lang=en

**Comment by giss69** [comment]
Danke Thomas,

habe jetzt mittlerweile selber rausgefunden! Läuft jetzt 1A. Danke!
Viele Grüße 
Andreas
